version: "3.1"

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - type: volume
        source: app
        target: /app
      - type: bind
        source: ./
        target: /usr/app

  database:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongodb
        target: /mongodb
      - type: bind
        source: ./storage/mongodb
        target: /var/lib/mongodb
    restart: always

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: redis
        target: /redis
      - type: bind
        source: ./storage/redis
        target: /data
    restart: always

volumes:
  app:
  mongodb:
  redis:
