version: "3.1"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "80:3333"

  database:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongodb
        target: /mongodb
      - type: bind
        source: /data/db/
        target: /var/lib/mongodb
    restart: always

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: redis
        target: /redis
      - type: bind
        source: /data/cache
        target: /data
    restart: always

volumes:
  mongodb:
  redis:
