version: "3.1"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./storage/mongodb:/var/lib/mongodb
      - ./mongo-init.js://docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: 123
          MONGO_INITDB_DATABASE: app
    restart: always

  cache:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data
    restart: always
