version: "3.1"

services:
  app:
    build: .
    command: npm start
    ports:
      - "80:3333"

  database:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - /data/db/:/var/lib/mongodb
      - /mongo-init.js://docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: 123
          MONGO_INITDB_DATABASE: app
    restart: always

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - /data/cache:/data
    restart: always