version: "3.1"

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - "./:/usr/app"

  database:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - ./storage/mongodb:/var/lib/mongodb
    restart: always

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis:/data
    restart: always